[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_counter = "FvWM5Lq2fFX2o65Tpr5RyWMFbtPELYT4d3cGFimSr3CH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
