[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
movie_review = "8iufEv7F5kQ5TW62WA27aoqAnFS3qBusRXwfuKWpNqEG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
